version: '3'

services:
  dashboard:
    build: .
    command: node dashboard.js
    env_file: secrets.env
    links:
      - redis
    restart: always
  worker:
    build: .
    command: node worker.js
    env_file: secrets.env
    links:
      - redis
    restart: always
  redis:
    image: redis
    volumes:
      - ./redis:/data
    restart: always
